# CUDA_VISIBLE_DEVICES=5 python main.py --gnn-type gat --seed 1 --loss curri-loss
# CUDA_VISIBLE_DEVICES=5 python main.py --gnn-type gat --seed 2 --loss curri-loss
# CUDA_VISIBLE_DEVICES=5 python main.py --gnn-type gat --seed 3 --loss curri-loss
# CUDA_VISIBLE_DEVICES=5 python main.py --gnn-type gat --seed 4 --loss curri-loss
# CUDA_VISIBLE_DEVICES=5 python main.py --gnn-type gat --seed 5 --loss curri-loss
CUDA_VISIBLE_DEVICES=5 python main.py --gnn-type gat --seed 1 --loss curri
CUDA_VISIBLE_DEVICES=5 python main.py --gnn-type gat --seed 2 --loss curri
CUDA_VISIBLE_DEVICES=5 python main.py --gnn-type gat --seed 3 --loss curri
CUDA_VISIBLE_DEVICES=5 python main.py --gnn-type gat --seed 4 --loss curri
CUDA_VISIBLE_DEVICES=5 python main.py --gnn-type gat --seed 5 --loss curri