# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gat --seed 1 --feature-level global-local
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gat --seed 2 --feature-level global-local
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gat --seed 3 --feature-level global-local
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gat --seed 4 --feature-level global-local
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gat --seed 5 --feature-level global-local
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gat --seed 1 --feature-level global
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gat --seed 2 --feature-level global
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gat --seed 3 --feature-level global
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gat --seed 4 --feature-level global
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gat --seed 5 --feature-level global
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gat --seed 1 --feature-level local
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gat --seed 2 --feature-level local
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gat --seed 3 --feature-level local
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gat --seed 4 --feature-level local
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gat --seed 5 --feature-level local
CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type graphsage --seed 1 --feature-level global
CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type graphsage --seed 2 --feature-level global
CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type graphsage --seed 3 --feature-level global
CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type graphsage --seed 4 --feature-level global
CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type graphsage --seed 5 --feature-level global
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gcn --seed 1 --feature-level global
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gcn --seed 2 --feature-level global
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gcn --seed 3 --feature-level global
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gcn --seed 4 --feature-level global
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gcn --seed 5 --feature-level global
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gin --seed 1 --feature-level global
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gin --seed 2 --feature-level global
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gin --seed 3 --feature-level global
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gin --seed 4 --feature-level global
# CUDA_VISIBLE_DEVICES=4 python main.py --loss mse --gnn-type gin --seed 5 --feature-level global